backend:
  repository: 047385030300.dkr.ecr.us-east-1.amazonaws.com/netflix-devops-backend
  tag: 25

frontend:
  repository: 047385030300.dkr.ecr.us-east-1.amazonaws.com/netflix-devops-frontend
  tag: 25

service:
  backendPort: 5000
  frontendPort: 80