apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend
  labels:
    app: netflix-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
      labels:
        app: netflix-frontend
    spec:
      containers:
      - name: netflix-frontend
        image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80