apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-backend
  labels:
    app: netflix-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-backend
  template:
    metadata:
      labels:
        app: netflix-backend
    spec:
      containers:
      - name: netflix-backend
        image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000